name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for backend
        working-directory: ./express-backend
        run: npm install

      - name: Install dependencies for frontend
        working-directory: ./user-management
        run: npm install

      - name: Run tests for backend
        working-directory: ./express-backend
        run: npm test

      - name: Run tests for frontend
        working-directory: ./user-management
        run: npm test

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push my-app
